steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'byteschneiderei/medium-rss-api:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/medium-rss-api:latest']
