name: ci
on:
  push:
    branches: master

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    env: 
      VERSION: $( cat VERSION )
      DOCKERHUB_REPO: byteschneiderei/medium-rss-api
      GITHUB_REPO:  docker.pkg.github.com/byteschneiderei/medium-rss-api/medium-rss-api
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Packages
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build 
        run:  docker build --tag "${{ env.DOCKERHUB_REPO }}:${{ env.VERSION }}" .
      -
        name: Push
        run: |
          docker push ${{ env.DOCKERHUB_REPO }}:${{ env.VERSION }}
          docker tag ${{ env.DOCKERHUB_REPO }}:${{ env.VERSION }} ${{ env.DOCKERHUB_REPO }}:latest
          docker push ${{ env.DOCKERHUB_REPO }}:latest
          docker tag ${{ env.DOCKERHUB_REPO }}:latest ${{ env.GITHUB_REPO }}:${{ env.VERSION }}
          docker push ${{ env.GITHUB_REPO }}:${{ env.VERSION }}
          docker tag ${{ env.GITHUB_REPO }}:${{ env.VERSION }} ${{ env.GITHUB_REPO }}:latest
          docker push ${{ env.GITHUB_REPO }}:latest
      
