name: ci
on:
  push:
    branches: master

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    env: 
      VERSION: $( cat VERSION )
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build 
        run:  docker build --tag "docker.pkg.github.com/byteschneiderei/medium-rss-api/medium-rss-api:${{ env.VERSION }}" .
      -
        name: Push Version
        run:  
          docker push docker.pkg.github.com/byteschneiderei/medium-rss-api/medium-rss-api:${{ env.VERSION }}
      -
        name: Push Latest
        run:  docker push docker.pkg.github.com/byteschneiderei/medium-rss-api/medium-rss-api:latest
      
