name: pull_request
on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Unit Tests
        run: make test

  build-docker-image:
    runs-on: ubuntu-latest
    env: 
      VERSION: $( cat VERSION )
      DOCKERHUB_REGISTRY: byteschneiderei/medium-rss-api
      GITHUB_REGISTRY:  docker.pkg.github.com/byteschneiderei/medium-rss-api/medium-rss-api
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Packages
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build 
        run:  docker build --tag "${{ env.DOCKERHUB_REGISTRY }}:${{ env.VERSION }}" .


